- name: dealear a variable at play level
  hosts: all
  connection: local
  vars:
    URL: www.youtube.com
  tasks:
    - name: access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}